### PR TITLE
added 2 additional migration tests

### PR DESCRIPTION
**Pull request by passsy**

### CODE REVIEW

**Comment by jannisveerkamp** [comment]
You can also test:
Put 2 different values within one SharedPreferences file and only migrate one.
Check if the other is still present after the migration :smiley: 

It works. But while developing I had the fear it doesn't :fearful:

**Comment by passsy** [comment]
contributions are welcome :stuck_out_tongue_winking_eye:

**Comment by jannisveerkamp** [comment]
:watch: :no_entry_sign: :cry:

**Comment by jannisveerkamp** [comment]
will do will do...

**Pull request merged**
