### PR TITLE
Feature/exception handling and put remove improvements

### PR DESCRIPTION
**Pull request by passsy**
Same as #51 but merge into master

### CODE REVIEW

**Comment by mengdd** [comment]
@passsy Hi, thanks to your feedback on my [PR](https://github.com/grandcentrix/tray/pull/68), I just take a look at this one.
I think it's really a better approach to return a boolean flag to indicate the results when doing write operations.
But for the read operation, we still throw an exception when the cursor is null, which we catch in `getVersion` but not for the other Uris. So there might be situation when version changed successfully but  the following query still throws. That way, user will have try catch every query. Is that better to return a empty or default value?

**Comment by passsy** [comment]
@mengdd all possible `ContentProvider` exceptions are now catched except for `int getVersion()` which is part of the public API but not very often used.

- `get(key)` (all variations) catched, return null (or default) on error
- `getAll()` catched, returns empty list on error
- `put(item)` (all variations) catched, return true when successful written >1 item
- `remove(key)` catched, returns true when deleted >1 item
- `clear()` catched, returns true when completed without error (also true when deleted 0 items)
- `wipe()` catched, returns true when completed without error (also true when deleted 0 items)
- `setVersion(int)` catched, returns true when changed
- `getVersion()` **checked Exception**, return the version and throws when the read fails

@jannisveerkamp review please

**Comment by mengdd** [comment]
@passsy just take a look at the latest codes, good work!

**Comment by jannisveerkamp** [comment]
In addition `Tray.wipe()` could return the result from the TrayProviderHelper.

**Comment by rberghegger** [comment]
@passsy looks great so far!

**Pull request merged**
